### ISSUE TITLE
Recommandations :

### ISSUE THREAD

**Issue by juliensailly** [AlensoLopes/BattleShip#2]
- Affichage sur le plateau des cases touchées par l'adversaire et celle touchées par le joueur
- Faire en sorte qu'un bateau soit touché-coulé en plusieurs fois 
- Faire en sorte que le bot ne puisse pas cibler 2 fois un même endroit

**Comment by AlensoLopes** [comment]
L'affichage des tirs sera disponible lors de la sortie de l'interface !

**Comment by juliensailly** [comment]
Superbe !
